version: '3.7'

services:

  dockerui:
    container_name: dockerui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'